# This file based on https://gist.github.com/mwouts/9842452d020c08faf9e84a3bba38a66f
# See: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
# 2020-06-22 - slg - customized
# 2020-06-27 - slg - expanded to G++ for MacOS
#
name: CI (python)
on: [push, pull_request]

env:
  COVERAGE_OS: ubuntu-latest
  COVERAGE_PYTHON_VERSION: 3.13

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: ['3.9','3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -r requirements.txt ];     then pip install -r requirements.txt ;     fi
          if [ -r requirements-dev.txt ]; then pip install -r requirements-dev.txt ; fi

      - name:  Install xmllint on ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install --yes libxml2-utils

      - name: Pre-commit Checks
        run: |
          pip -q install pre-commit
          pre-commit run --all-files

      - name: Make check
        run: make check

      - name: Make check-tools
        run: make check-tools

      - name: Test with pytest
        run: pytest --cov=dfxml --cov-report=xml .

      - name: Upload to codecov.io
        if: matrix.os == env.COVERAGE_OS && matrix.python-version == env.COVERAGE_PYTHON_VERSION
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./coverage.xml
